# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DccMcp.DccMcpCli
PackageVersion: 0.20.37
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dcc-mcp-cli.exe
  PortableCommandAlias: dcc-mcp-cli
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dcc-mcp/dcc-mcp-core/releases/download/v0.20.37/dcc-mcp-cli-0.20.37-windows-x86_64.zip
  InstallerSha256: 8037CB4899C6C88CA62C9297CFAB5BD6F9247B6335ABD0E952EA3686CE87D6E3
ManifestType: installer
ManifestVersion: 1.12.0
